### ISSUE TITLE
ember-cli installation error

### ISSUE THREAD

**Issue by futurist** [tsteuwer/emberloop#19]
when on **Step 9** after execute `docker-compose up` command, error occur and stop with below msg:

```
Step 9 : RUN npm install -q -g ember-cli@1.13.8
 ---> Running in 9ae6a8f36cf8
npm ERR! Linux 4.1.13-boot2docker
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-q" "-g" "ember-cli@1.13.8"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7

npm ERR! shasum check failed for /tmp/npm-6-4bf827c2/registry.npmjs.org/ember-cli/-/ember-cli-1.13.8.tgz
npm ERR! Expected: 9a116a0be1c73f9d6fdeb50042f207ab33f6e5c6
npm ERR! Actual:   a30a120b12dd5f2b6a3623f3dd5263896028b7b2
npm ERR! From:     https://registry.npmjs.org/ember-cli/-/ember-cli-1.13.8.tgz
```

seems checksum don't match, and `ember-cli` don't installed.

OSX: 10.9.5
Docker version 1.9.1, build a34a1d5
docker-compose version 1.5.2, build 7240ff3

**Comment by tsteuwer** [comment]
@futurist , this seems like an issue with Ember-CLI, not this repository. I'd recommend posting an issue on [their repository](https://github.com/ember-cli/ember-cli).

**Comment by futurist** [comment]
the `ember-cli` responsed they cannot control.
maybe use another ember-cli version to test?

**Comment by tsteuwer** [comment]
They said it might be an npm issue. You should contact them or try changing it on your container
